[phases.setup]
nixPkgs =  ["nodejs_20"]

[phases.install]
cmds = ["yarn install --no-progress --silent"]

[phases.build]
cmds = ["yarn build"]

[start]
cmd = "yarn serve"

[variables]
NODE_ENV = 'production'
